apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-m2e3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-m2e3
    app.kubernetes.io/part-of: tkrw-pr712-0075-0075-app
  name: devfile-sample-m2e3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-m2e3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-m2e3
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-m2e3@sha256:fdcdcd62e2c9ddda5bb3ff6ca4c4f6ddacc95a06bc99c50d82290787391f4166
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
